service: myapp

provider:
  name: aws
  runtime: python3.7
  stage: default
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ queuelambdafunction1, Arn ]

custom:
  env: ${opt:stage, self:provider.stage}
  resource_prefix: ${self:custom.env}-${self:service}
  queue-name-lambda_function1: ${self:custom.resource_prefix}-lambda_function1

functions:


  lambda_function1:
    handler: app/lambda_function1.lambda_handler
    environment:
      SQS_URL:
        Ref: queuelambdafunction1


  lambda_function2:
    handler: app/lambda_function2.lambda_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ queuelambdafunction1, Arn ]

resources:
  Resources:

    queuelambdafunction1:
      Type: AWS::SQS::Queue
      Properties:
          QueueName: ${self:custom.queue-name-lambda_function1}
