# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ develop, implement-github-based-CICD, implement-github-based-CD ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install NodeJS for serverless framework
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Installing requirements
      run: make requirements

    - name: Static code analysis (pylint tool)
      run: make lint

    - name: Code security checkings (bandit tool)
      run: make security

    - name: Unit tests
      run: make unittest

    - name: Code coverage
      run: make coverage

    - name: Deploy
      run: make deploy

    - name: End to End Tests
      run: make e2e-tests

    - name: Destroy
      run: make destroy
